language: objective-c
env:
  - SWIGLANG= CC=gcc-4.2 CXX=g++-4.2
  - SWIGLANG= CC=clang CXX=clang++
matrix:
  include:
    - env: SWIGLANG=csharp CC=clang CXX=clang++
    - env: SWIGLANG=go CC=clang CXX=clang++
    - env: SWIGLANG=guile CC=clang CXX=clang++
    - env: SWIGLANG=java CC=clang CXX=clang++
    - env: SWIGLANG=lua CC=clang CXX=clang++
    - env: SWIGLANG=perl5 CC=clang CXX=clang++
    - env: SWIGLANG=php CC=clang CXX=clang++
    - env: SWIGLANG=python CC=clang CXX=clang++
    - env: SWIGLANG=python PY3=1 CC=clang CXX=clang++
    - env: SWIGLANG=ruby CC=clang CXX=clang++
    - env: SWIGLANG=tcl CC=clang CXX=clang++
  allow_failures:
    - env: SWIGLANG=php CC=clang CXX=clang++
before_install:
  - date -u
  - uname -a
  - sw_vers
  - brew update
  - brew list
  - brew install pcre
  - brew install boost
  - if test "$SWIGLANG" = "csharp"; then brew install https://dl.dropboxusercontent.com/u/696131/Homebrew/mono.rb; fi
#  - if test "$SWIGLANG" = "go"; then go env | sed -e 's/^/export /' > goenvsetup && source goenvsetup && rm -f goenvsetup; fi # Until configure.ac is fixed
  - if test "$SWIGLANG" = "guile"; then Tools/brew-install guile; fi
  - if test "$SWIGLANG" = "lua"; then brew install lua; fi
  - if test "$SWIGLANG" = "python" -a "$PY3"; then brew install python3 && brew list -v python3; fi
  - ls -la $(which $CC)
  - ls -la $(which $CXX)
  - $CC --version
  - $CXX --version
script:
  - echo 'Configuring...' && echo -en 'travis_fold:start:script.1\\r'
  - ./autogen.sh && mkdir -p build/build && cd build/build && ../../configure $CONFIGOPTS
  - echo -en 'travis_fold:end:script.1\\r'
  - make -s $SWIGJOBS
  - ./swig -version && ./swig -pcreversion
  - if test -z "$SWIGLANG"; then make -s $SWIGJOBS check-ccache; fi
  - if test -z "$SWIGLANG"; then make -s $SWIGJOBS check-errors-test-suite; fi
  - echo 'Installing...' && echo -en 'travis_fold:start:script.2\\r'
  - if test -z "$SWIGLANG"; then sudo make -s install && swig -version && ccache-swig -V; fi
  - echo -en 'travis_fold:end:script.2\\r'
  - if test -n "$SWIGLANG"; then make -s check-$SWIGLANG-version; fi
  - if test -n "$SWIGLANG"; then make -k $SWIGJOBS check-$SWIGLANG-examples; fi
  - if test -n "$SWIGLANG"; then make -k $SWIGJOBS check-$SWIGLANG-test-suite; fi
  - echo 'Cleaning...' && echo -en 'travis_fold:start:script.3\\r'
  - make maintainer-clean
  - echo -en 'travis_fold:end:script.3\\r'
branches:
  only:
    - master
    - travis-osx

